### ISSUE TITLE
multicomposite-addon AEM 6.4 issue

### ISSUE THREAD

**Issue by dibyasagar87** [OlsonDigital/multicomposite-addon#11]
'Value.CONTENTPATH_ATTRIBUTE' deprecated in AEM 6.4. can you please update the 'Multicomposite.java' file ? @lykorian

**Comment by dibyasagar87** [comment]
@michaelhodgdon Components with Multicomposite fields are not retaining values after authoring. In my analysis I found that from the variable ''Value.CONTENTPATH_ATTRIBUTE'', we are getting the path of that component values and since its deprecated we are no longer able to get those from jcr properties.

**Comment by michaelhodgdon** [comment]
This has been fixed

**Comment by dibyasagar87** [comment]
@michaelhodgdon I don't see the fix in 'Multicomposite.java'. Can you tell me what's the fix or which branch I should check for the fix?
